### ISSUE TITLE
Option for Vertex missing in the list of models (frontend)

### ISSUE THREAD

**Issue by charl3sj** [rnadigital/agentcloud#250]
**Describe the bug**
We've added support for Gemini chat model via VertexAI in the backend but the corresponding frontend changes are missing.

**Expected behavior**
User should be allowed to select Vertex and Gemini as a model.

**Screenshots**
![Screenshot 2024-06-20 at 1 02 23 PM](https://github.com/rnadigital/agentcloud/assets/1017170/7e532497-6eb6-4ae0-b857-17c79f018b59)

**Refer**
https://github.com/rnadigital/agentcloud/blob/e19ff6c75f44acfd5cdead679ee7b3ac0481453d/agent-backend/src/models/mongo.py#L29
![Screenshot 2024-06-20 at 1 11 34 PM](https://github.com/rnadigital/agentcloud/assets/1017170/6caceb32-760f-4d0d-8682-84220684799f)

**Comment by tomlynchRNA** [comment]
@anada10 I remember now, this wasn't made available in frontend yet because vertex only takes credentials from an environment variable. We can't support users providing their own credentials: https://python.langchain.com/v0.2/docs/integrations/chat/google_vertex_ai_palm/#credentials

**Comment by anada10** [comment]
@tomlynchRNA what if we use OAUTH for GCP instead?

**Comment by tomlynchRNA** [comment]
@anada10 I don't think so, it has to be the credentials (like credentials json). They make it pretty clear in their docs/code comments:
![image](https://github.com/rnadigital/agentcloud/assets/111718755/62988c2a-05f0-424d-9ed6-d02a297306cf)


But good news, I checked the ChatVertexAI source code in Google repo and found this:

https://github.com/langchain-ai/langchain-google/blob/main/libs/vertexai/langchain_google_vertexai/chat_models.py#L648C9-L648C17

**So, turns out there is an undocumented option to pass the credentials directly just like other models :smile:** 

We need an update in the webapp and agent-backend to pass `credentials`, `project` and `location`

cc @charl3sj
